### ISSUE TITLE
We should use par file if present

### ISSUE THREAD

**Issue by labrosse** [mulvrova/StagPy#7]
-p and -n options could have default values taken from par file if present.

**Comment by amorison** [comment]
Done. -n (--name) default value is set in config.parse_args() with the value output_file_stem from par file (or 'test' if no par file is found).

-p option should contain the path to the StagYY run directory (hence the one containing the par file), so it isn't set with any value from par file.

**Comment by labrosse** [comment]
I thought that -p was pointing to the directory where the out files from Stagyy are, which is often different from the dir where par is. This is specified as stem in par.

**Comment by amorison** [comment]
The example I put in the readme is misleading, I should rewrite it. Let's say the run directory is called `runStag`. It will contains a par file, in which `output_file_stem` will be for example `+op/test`. By setting `args.path` to the path towards `runStag` and `args.name` to `+op/test`, we don't have to worry about whether the output files are or not in a subdirectory since `args.path + args.name` will give us the right prefix name for all the output files.

**Comment by labrosse** [comment]
Yes, that's right!
